module.exports = {
  User: require('./User'),
  Category: require('./Category'),
  Product: require('./Product'),
  ProductVariant: require('./ProductVariant'),
  Cart: require('./Cart'),
  Wishlist: require('./Wishlist'),
  Review: require('./Review'),
  Coupon: require('./Coupon'),
  Address: require('./Address'),
  Order: require('./Order'),
  OrderItem: require('./OrderItem'),
  Payment: require('./Payment'),
  Inventory: require('./Inventory'),
  Banner: require('./Banner'),
  FAQ: require('./FAQ'),
  Notification: require('./Notification'),
  SiteSettings: require('./SiteSettings'),
  Newsletter: require('./Newsletter'),
};
